apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kumar-deployment
  namespace:kumar-cicd
spec:
  selector:
    matchLabels:
      app: kumar
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kumar
    spec:
      containers:
      - name: kumar
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/kumar-cicd:latest
        ports:
        - containerPort: 80
