apiVersion: v1
kind: Service
metadata:
  name: kumar-service
  namespace: kumar-cicd
spec:
  type: LoadBalancer
  selector:
    app: kumar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
